apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-consumer
  ports:
    - protocol: TCP
      port: 80   # the port advertised by the service to the cluster
      targetPort: 30092  # port used by the running container inside the pod
