producer-job:
apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
spec:
  template:
    spec:
      containers:
      - name: producer
        image: 172.16.4.133:5000/team9/producer_image:latest
        env:
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # This assigns a unique producer ID based on the pod name
        volumeMounts:
        - name: output-volume
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-pvc  # Use a PVC for persistent storage
  backoffLimit: 4
