apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
spec:
  template:
    spec:
      containers:
      - name: consumer
        image: 172.16.4.133:5000/team9/simple_image:latest
      restartPolicy: Never
  backoffLimit: 1
